
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Predator
 */
public class VotePanel extends javax.swing.JPanel {

    /**
     * Creates new form VotePanel
     */
    public VotePanel() {
        initComponents();
    }

    public JLabel getLblPosition() {
        return lblPosition;
    }

    public JPanel getContentVotePanel() {
        return ContentVotePanel;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentVotePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPosition = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        ContentVotePanel.setLayout(new javax.swing.BoxLayout(ContentVotePanel, javax.swing.BoxLayout.Y_AXIS));
        add(ContentVotePanel, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 70));

        lblPosition.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPosition.setText("Position");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentVotePanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPosition;
    // End of variables declaration//GEN-END:variables
}
